spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Pod Resources
resources:
  requests:
    cpu: 0.01
    memory: 1354Mi
  limits:
    cpu: 1
    memory: 2048Mi
configMaps:
  env: qa
# JVM Params
javaOptsAppend:
  xss: 512k
  xms: 2g
  xmx: 4g
# Honeycomb Agent
honeycomb:
  agent: -javaagent:/application/honeycombagent.jar
  service_name: "ol-pl-service"
  traces_endpoint: "http://opentelemetry-collector.observability.svc.cluster.local:4320/v1/traces"
  metrics_endpoint: "http://opentelemetry-collector.observability.svc.cluster.local:4320/v1/metrics"
  traces_exporter: "otlp"
  otlp_protocol: "http/protobuf"
#Route
route:
  enabled: false
  fqdn: plservice.test1.adesa.com
#Route Alternate Gateway
alternate_route_gateway:
  fqdn: api.test1.kar-hosting.com
#DB Configurations
db_host:
  - 10.200.165.101
db_password: env$AQIDAHgS+BKcDc5nTrfaJf6S5RtwALUEALEZOVb+nNAVmKIdCQE1TqSp82ED86dZ+FEXWMcTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMReiv7lRXZJMtyxPvAgEQgDsDdVYc67n72XcAVKNSFfeXXU1oe4UwUbO7OBx2ONJKcTplaCBeT9R51nVbj4hHoB07QSuIobkayCJxcA==$TD/OKjrD2yN36K8jbcG5Qg==:qWlHRBsn736hoELbVFu9Zg==
db_service_name: AUCS
hibernate.cache.use_query_cache: true
hibernate.cache.use_second_level_cache: true
hibernate.generate_statistics: true
hibernate.cache.use_structured_entries: true
hibernate.cache.provider_class: org.hibernate.cache.TreeCacheProvider
net.sf.ehcache.configurationResourceName: /ehCache.xml
hibernate.show.sql: true
commonBI.login.service.base.url: https://login2.test1.adesa.com/
commonBI.imola.engine.base.url: https://api.test1.kar-hosting.com/
commonBI.logger.api.base.url: https://api.test1.kar-hosting.com/
commonBI.contact.us.dest.email: Test1Emails@openlane.com
image.server.path: https://adesa.test1.kar-media.com/display.php?img=
contextSignerSealer.password: env$AQIDAHgS+BKcDc5nTrfaJf6S5RtwALUEALEZOVb+nNAVmKIdCQGIWW91b8Y7+vMcayhNtnBIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtwpbwh6Q4FRivBAlAgEQgDuRkYoLBnvVzHyWFlOvEkPvnjTAKSpAVliHroPj2c5BR9WpORHUaJI22b4fQinvpySVFTUW+uPBv8FnBA==$JLp9fT6ATDEhmHeUL+YgFw==:N9TVCNdwjoHgiqma90vQRLeyWDwzp44UUyDEI+sFMYGrKWEsGXSyChL855LfSbYQlrNsgRfpkpCVO3Xo7lNVPA==
ford.ptp.soapActionName: requestPretermPrice
ford.ptp.cookieName: WSL-credential
ford.ptp.userName: q-atc
ford.ptp.password: env$AQIDAHgS+BKcDc5nTrfaJf6S5RtwALUEALEZOVb+nNAVmKIdCQHYsmnu8sTXfSH7u1VZgZ2uAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMa0NtpWfLcKJE/scHAgEQgDtn+KTqlP+V4wHyLvzYltJOi2GGoLo9GJIG2yWO8M1OYHkjnYuHy8MrB5OtHjexdlxvRCW2JeNxeTBaSA==$ibvJwiaAb4XepzCQX71hEQ==:8N5knv+JmLRmY9mP3Ep2chtM5w5kegU+i1jrgWHA5IBQPygeCCymZRANIdQFVg9i
ford.ptp.appURL: https://webqa.uvis.ford.com/uvis/webServices
ford.ptp.authURL: https://www.wslb2b.ford.com/auth.cgi
ford.ptp.cookieValue: XSTW2l8GCloBAD4ABHVzZXJpZD1mY3Zyb3BscQBpcGFkZHI9MTkuMTExLjYuMjAzXzE5LjExMS42LjIwNAAAAENOPXdzbHY0LWludGVybmFsAFTgB8BwWN50m2ItScXKodqCUv/biNnpdnzd7zT/wUGfnL2zP8JK/FMrKl++BOvz2zWKGhQsNpkP12OMnzje//sqmrvNGBLLYIPGWMV86S+r+FqdQP22iJ7748e01WTDze5JNSU2n7zGj+WnYiO+99apwT6CeuUGQxaCT9gVwRps
# Notification
notification.service.queue.manager: CARQMGT01
notification.service.port: 1416
notification.service.host: carqmgt01.mq-test-ol-ha.svc.cluster.local
okta.Token.Url.Issuer: https://openlane-np.oktapreview.com/oauth2/aus3lupblcwotNDjJ0x7
ford.build.data.oauth.token_url: https://login.microsoftonline.com/c990bb7a-51f4-439b-bd36-9c07fb1041c0/oauth2/v2.0/token
ford.build.data.oauth.client_id: bf024453-7426-4418-befc-e3aed7cc185f
ford.build.data.oauth.grant_type: client_credentials
ford.build.data.oauth.scope: f58af914-8ec5-47ad-9469-b51906795f1a/.default
ford.build.data.oauth.client_secret: env$AQIDAHicP629eYLKU3LOCRft9HDIQUFQ++8m1cD+nhdtADxP4AEN0775F+/6vp/lEvPd+XN2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW20QRZ1WKQTTC3glAgEQgDtf4+ncII0C4CsVzbjD2OsBjG1ul4ylhR7rwMSE7kyo07ZzWJnHkIy2XE8AquHZnHxo16l3BVO/GH2Evg==$KKrdfAaDopzzN9sl3s/55A==:fmCEW+D8XOn1T4AR7stsypiWq/JzQzSZayjq4fJiNaLnaTeHTihVILUbiFpwdW5E
ford.build.data.url: https://api.vehicle.ford.com/vehicle-data-as-built/vehicles/build-data
httpGateway: publicocp
httpGatewayGA: publicqa
# PTMP Token Configuration
ford.ptmp.token.grant_type: client_credentials
ford.ptmp.token.client_id: 1c6466e8-c8e1-46d4-91e7-3f4e51bd8197
ford.ptmp.token.client_secret: env$AQIDAHjQ3nvjmpgYbECeJPJ0s6ubhw8Hd3qohT357gdk6Y0o6AH2MM12/diUVVdqXUoP7n0tAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQModWXbzQ98xlY6VPZAgEQgDs8tF8+eqkiZnFEvvGsNFn+97jVqKMUjJ90ntmRE8u8rGa5XkVFXOumxNxnnaJmNlanDdsIdttveonL8g==$5Y5HwSTQA7WoOai42qdxNg==:AYZzqEd1OFUF+2wO+lrxRYLu3KJGtAC5udT2xotniHFg8ZiouI8S6vFCYAJgxaOD
ford.ptmp.token.scope: api://91407b48-53a7-4ee5-b9e0-6753dcecb21a/.default
ford.ptmp.token.ford_token_url: https://login.microsoftonline.com/azureford.onmicrosoft.com/oauth2/v2.0/token
ford.ptmp.appURL: https://api-qat.fordcredit.com/uvis/preterm-soap/uvis/api/webServices

ford.build.data.oauth.client_secret: KB_8Q~aknfrfLYbLyzurQkPznUiCDzy5cUjKkaYf
